bracketSpacing: true
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 4
trailingComma: "all"
useTabs: false

overrides:
  - files: ["*.json", "*.md", "*.yml"]
    options:
      tabWidth: 2
